volumes:
  dba-data: {}

services:
  reportapi:
    build: 
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: reportapi
    container_name: report_local_fastapi
    env_file:
      - .envs/.local/.fastapi
      - .envs/.local/.dba
    ports:
      - '8080:8000'
    command: /start

  dba:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: dba
    container_name: report_local_dba
    env_file:
      - .envs/.local/dbs/.dba
    ports:
      - '5434:5432'
    volumes:
      - dba-data:/var/lib/postgresql/data

