[project]
name = "reportapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.7",
    "gunicorn>=25.0.3",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.40.0",
]
